### ISSUE TITLE
Traceback

### ISSUE THREAD

**Issue by ghost** [voidbar/forwardgram#1]
Logging in with the phone number and code is working, after that i get this:

> Traceback (most recent call last):
>   File "forwardgram.py", line 40, in <module>
>     start(config)
>   File "forwardgram.py", line 18, in start
>     for d in client.iter_dialogs():
>   File "C:\Users\Max\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telethon\requestiter.py", line 84, in __next__
>     return self.client.loop.run_until_complete(self.__anext__())
>   File "C:\Users\Max\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 584, in run_until_complete
>     return future.result()
>   File "C:\Users\Max\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telethon\requestiter.py", line 59, in __anext__
>     raise StopAsyncIteration
> StopAsyncIteration

**Comment by voidbar** [comment]
Do you have any dialogs open in your account?

**Comment by ghost** [comment]
Yes, including the ones i wanted to forward from/to

**Comment by voidbar** [comment]
Are you sure that you are trying to forward messages from _channels_ rather then regular chats?

**Comment by sHaDoW8185** [comment]
I am currently running this script and it seems to be working.  Wanted to ask if you will allow the option to remove the text "forwarded from xxxxxx" so that it looks like a regular message submitted in the channel?

**Comment by voidbar** [comment]
Still waiting for your response

**Comment by voidbar** [comment]
Closing because of lack of response
