### ISSUE TITLE
input_channel_names with emoji

### ISSUE THREAD

**Issue by kenmaxnejp** [voidbar/forwardgram#10]
Sorry I have another problem.
I am forwarding message from channel with names consist of emoji. At input_channel_names I use CLDR short name (something like :grinning_face_with_big_eyes: or :winking_face_with_tongue:)to represent emoji but look like it didn't work. Any suggestions are welcome, thanks!

**Comment by JuanMiguelPR** [comment]
Hi, it´s been a good time since your last question and well, once again, the answer will be RE :)

Don't get me wrong, just go and google, you'll go around it.

**Comment by voidbar** [comment]
hi @kenmaxnejp,
Your problem does not replicate in my test environment. I managed to add a channel with an emoji in its name. 
Maybe try to switch an editor, and copy the channel name from telegram desktop interface. 
Good luck!
