### ISSUE TITLE
Filter Type of Message

### ISSUE THREAD

**Issue by bernardopribeiro** [voidbar/forwardgram#12]
Hello, i want to know if is possible to filter the message and only send movies or photos with out text...
Thank you

**Comment by voidbar** [comment]
Well, you can do that on your own if you just change the `handler(event)` function. I see no reason to add that here, because its not the purpose of this project. You should look at `telethon` api to figure out how it is down, shouldn't be too complicated 😄 

Good luck!

**Comment by bernardopribeiro** [comment]
Imagine if someone send something like join Thais group with a photos, i want to send ONLY the image pls
