### ISSUE TITLE
unacceptable character!

### ISSUE THREAD

**Issue by ibimo** [voidbar/forwardgram#17]
Hi, when i paste groups with names like:  💎Kingdom 
It says: "Unacceptable character" if i try to use the @Channelname doesn't find anything
it's possible to bypass this?

**Comment by ekkutlu** [comment]
I have same problem
Did you find any solution? I tryed convert emoji to unicode but it didn't work... :((

**Comment by voidbar** [comment]
Hi, you can now use groups ids instead of the channel name. https://github.com/voidbar/forwardgram/pull/27
