### ISSUE TITLE
Feature Request (Non-Issue)

### ISSUE THREAD

**Issue by jbgoldrich** [voidbar/forwardgram#2]
I am currently running this script and it seems to be working. Wanted to ask if you will allow the option to remove the text "forwarded from xxxxxx" so that it looks like a regular message submitted in the channel?

**Comment by voidbar** [comment]
You can use the function `send_message` instead of `forward_message`. Although this way you'll have to take care of text and media separately, which I decided not to. After all, this project if for **forwarding** messages.
Closed for now as this is a non-issue
