### ISSUE TITLE
Dockerize Forwardgram

### ISSUE THREAD

**Issue by raftheunis87** [voidbar/forwardgram#20]
Hey!

First of all, great job on Forwardgram! :)

I'm running Forwardgram on my Synology NAS right now with Docker :). The biggest reason for me being:
- I don't want to clutter with python on my NAS
- I want the container to restart automatically if my nas was down due to a power outage

However, when starting Forwardgram, you get this wizard thing that you have to do manually. Is there a way to work around this? I mean: it should be possible to just do this wizard once and reuse the credentials?

Kind regards,

Raf

**Comment by tnshibu** [comment]
Hi Raf,
Please read about the -v option in docker run command.
Once you are comfortable with the -v parameter, you can map the configuration folder to the container program folder.

**Comment by voidbar** [comment]
Hi. @tnshibu is right, you can easily create a docker based on `python:latest` and mount the session directory using the `-v` option. Closing.
