### ISSUE TITLE
[Feature Request] is it possible to have session file in custom folder

### ISSUE THREAD

**Issue by tnshibu** [voidbar/forwardgram#21]
Hi,
The config.yml can be placed in any location and the path provided at runtime by specifying on the command line
python3 forwardgram.py mypath/config.yml

Is it possible to also provide the session file path also as a parameter to the program? something like below?
python3 forwardgram.py mypath/config.yml anotherpath/customsess.session

**Comment by voidbar** [comment]
Hii @tnshibu, seems like from `telethon` docs you can specify full path in the client's c'tor. Meaning you should be able to pass full path to forwardgram in the `session_name` config field (https://github.com/voidbar/forwardgram/blob/master/config.yml-sample#L3) . Closing this for now, lmk if you are having any trouble
