### ISSUE TITLE
Want to Copy paste mode

### ISSUE THREAD

**Issue by TSpidermanBoss** [voidbar/forwardgram#4]
please this forward messages change script into copy and paste mode.

**Comment by voidbar** [comment]
What does that mean?

**Comment by JuanMiguelPR** [comment]
I think it means to forward the messages without telegram showing the chat/channel where it is forwarded from.
From what I saw, I don't know if it's possible with an specific method

**Comment by smahesh29** [comment]
For copy and paste mode use
`await client.send_message(output_channel_entity, event.message)`
in place of `await client.forward_messages(output_channel_entity, event.message)`

This will not show forwarded from.

**Comment by bernardopribeiro** [comment]
And copy images, and reply from past message ?

**Comment by smahesh29** [comment]
@bernardopribeiro what's your question?  Please ask it properly.

**Comment by open4profit** [comment]
i want to copy paste message along with replies. 
For ex. for replies, message should come along with original msg, to which reply is made.

**Comment by bernardopribeiro** [comment]
Some updates here ?

**Comment by voidbar** [comment]
Looks like @smahesh29 answered the question. Closing this :)
