### ISSUE TITLE
Forwarding to more than one channel!

### ISSUE THREAD

**Issue by JuanMiguelPR** [voidbar/forwardgram#5]
Hi!

First I'll like to thank you. It has worked perfectly for me. I had used other ways of achieving automatic forwarding, but finally this one is suitable for my needs.

I wanted to ask if it would be possible to forward to multiple or different channels, e.g. I'm part of 4 channels 1, 2, 3 & 4. And forward to two channels from which I'm an admin separating the sources:
Forwarded channel 1: Channels 1 & 2.
Forwarded channel 2: Channels 3 & 4.

I'm sure that can be achievable by making some modifications and maybe using some identifiers for the different channels, but I'm not pretty sure where to start.

**Comment by voidbar** [comment]
Why did you close the issue?

**Comment by JuanMiguelPR** [comment]
Cause I solved it! Wasn't difficult, just modified a bit the config file and the code. The thing was that I opened the issue just after trying the code once, without taking much of a look to it.

I also faced a little problem with the channel I wanted to forward from, as it had a couple emojis as part of the name, but solved it easily with re

**Comment by tzagim** [comment]
@jmgv098 U can share your code?
